In [5]:
import open3d as o3d


color_raw_0 = o3d.io.read_image('./dataset/realsense/color/cam0_0.png')
depth_raw_0 = o3d.io.read_image('./dataset/realsense/depth/cam0_0.png')
rgbd_image_0 = o3d.geometry.RGBDImage.create_from_color_and_depth(color_raw_0, depth_raw_0)
print(rgbd_image_0)


RGBDImage of size 
Color image : 2448x2048, with 1 channels.
Depth image : 2448x2048, with 1 channels.
Use numpy.asarray to access buffer data.


In [6]:
# Camera intrinsic parameters built into Open3D for Prime Sense
w0 = 2480
h0 = 2048
fx0 = 3.40279761e+03
fy0 = 3.41122021e+03
cx0 = 1.24198049e+03
cy0 = 1.08247093e+03
intrinsic_0 = o3d.camera.PinholeCameraIntrinsic(w0, h0, fx0, fy0, cx0, cy0)
print(intrinsic_0.intrinsic_matrix)

[[3.40279761e+03 0.00000000e+00 1.24198049e+03]
 [0.00000000e+00 3.41122021e+03 1.08247093e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [7]:
intrinsic_1 = o3d.camera.PinholeCameraIntrinsic(w0, h0, fx0, fy0, cx0, cy0)
rgbd_image_1 = o3d.geometry.RGBDImage.create_from_color_and_depth(color_raw_0, depth_raw_0)

In [10]:
# Create the point cloud from images and camera intrisic parameters
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image_0, intrinsic_0)
# Flip it, otherwise the pointcloud will be upside down.
pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
print(pcd)


PointCloud with 2828427 points.


In [9]:
axis_aligned_bounding_box = pcd.get_axis_aligned_bounding_box()
axis_aligned_bounding_box.color = (1, 0, 0)
oriented_bounding_box = pcd.get_oriented_bounding_box()
oriented_bounding_box.color = (0, 1, 0)
print(
    "Displaying axis_aligned_bounding_box in red and oriented bounding box in green ..."
)
o3d.visualization.draw(
    [pcd, axis_aligned_bounding_box, oriented_bounding_box])

RuntimeError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)

While executing:  | qhull Qt
Options selected for Qhull 2020.2.r 2020/08/31:
  run-id 1991439120  Qtriangulate  _pre-merge  _zero-centrum
  _max-width 2.8e-06  Error-roundoff 5.2e-21  _one-merge 3.7e-20
  _near-inside 1.8e-19  Visible-distance 1e-20  U-max-coplanar 1e-20
  Width-outside 2.1e-20  _wide-facet 6.3e-20  _maxoutside 4.2e-20

The input to qhull appears to be less than 3 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p2825979(v4): -1.4e-06 -1.1e-06 -3.9e-06
- p0(v3): 5e-07 9.4e-07 -3.9e-06
- p2490619(v2): 1.4e-06 -9.5e-07 -3.9e-06
- p631428(v1): -1.4e-06 2e-07 -3.9e-06

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 5.2e-21.  The center point, facets and distances
to the center point are as follows:

center point -2.437e-07 -2.314e-07 -3.922e-06

facet p0 p2490619 p631428 distance=    0
facet p2825979 p2490619 p631428 distance=    0
facet p2825979 p0 p631428 distance=    0
facet p2825979 p0 p2490619 distance=    0

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:  -1.431e-06  1.389e-06  difference= 2.82e-06
  1:  -1.109e-06  9.352e-07  difference= 2.044e-06
  2:  -3.922e-06  -2.225e-308  difference= 3.922e-06

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 5.2e-21.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.
